[tool.poetry]
name = "retfound-mae"
version = "0.1.0"
description = ""
authors = ["Mason Cleveland <mcleveland2@mgh.harvard.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7.6"
torch = "1.8.1"
torchvision = "0.9.1"
torchaudio = "0.8.1"
opencv-python = "4.5.3.56"
pandas = "0.25.3"
Pillow = "8.3.1"
protobuf = "3.17.3"
pycm = "3.2"
pydicom = "2.3.0"
scikit-image = "0.17.2"
scikit-learn = "0.24.2"
scipy = "1.5.4"
tensorboard = "2.6.0"
tensorboard-data-server = "0.6.1"
tensorboard-plugin-wit = "1.8.0"
timm = "0.3.2"
tqdm = "4.62.1"
visidata = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
